# Generated by Django 3.1.3 on 2020-12-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201202_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber_name',
            new_name='access_token',
        ),
    ]
